name: Create FoundryVTT Module Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build module
      run: npm run build
      
    - name: Validate version format
      run: |
        if [[ ! "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
          echo "Error: Version must be in format v1.0.0 or v1.0.0-beta"
          exit 1
        fi
        
    - name: Update module.json version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        VERSION_NUMBER="${VERSION#v}"  # Remove 'v' prefix
        jq --arg version "$VERSION_NUMBER" '.version = $version' module.json > module.json.tmp
        mv module.json.tmp module.json
        
    - name: Create release bundle
      run: |
        # Create a temporary directory for the bundle
        mkdir -p mallindor-rest
        
        # Copy required files to bundle directory
        cp module.json mallindor-rest/
        cp -r dist mallindor-rest/
        
        # Create the zip file
        zip -r mallindor-rest-${{ github.event.inputs.version }}.zip mallindor-rest/
        
    - name: Verify bundle contents
      run: |
        echo "Bundle contents:"
        unzip -l mallindor-rest-${{ github.event.inputs.version }}.zip
        
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Mallindor Rest Rules ${{ github.event.inputs.version }}
        body: |
          ## Installation
          
          1. Download the `mallindor-rest-${{ github.event.inputs.version }}.zip` file
          2. Extract it to your FoundryVTT `Data/modules/` directory
          3. Enable the module in your world settings
          
          ## Requirements
          - FoundryVTT v13+
          - D&D 5e system v5.0.0+
          - Socket.io module (socketlib)
          
          ## Features
          - Custom rest mechanics with exhaustion system
          - Partial healing during rests
          - Socket-based multiplayer support
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mallindor-rest-${{ github.event.inputs.version }}.zip
        asset_name: mallindor-rest-${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip
        
    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add module.json
        git commit -m "Update version to ${{ github.event.inputs.version }}" || exit 0
        git push
